
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argo-cd
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  service.email: |
    host: smtp.gmail.com
    port: 587
    from: fulcoivo@gmail.com
    insecure: "true"
  template.app-sync-failed: |
    email:
      subject: "ArgoCD: Falha na sincronização do app {{.app.metadata.name}}"
      body: |
        A aplicação {{.app.metadata.name}} falhou ao sincronizar.
        Status: {{.app.status.sync.status}}
        Health: {{.app.status.health.status}}
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
