apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivofulco/argocd-self-managed
    targetRevision: main
    path: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true