apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: somente-leitura
  source:
    repoURL: https://github.com/ivofulco/argocd-self-managed
    targetRevision: main  # ou a branch/tag desejada
    path: gitops/app-of-apps/cert-manager-v1.11.0
    helm:
      valueFiles:
        - values.yaml  # ajuste o path relativo conforme a estrutura
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
