apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd  # Este é o namespace onde o ArgoCD está instalado
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.13.0
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: true
        pushgateway:
          enabled: false
        server:
          service:
            type: ClusterIP
          persistentVolume:
            enabled: true
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
