apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd  # ou o namespace do Argo CD
spec:
  project: default

  source:
    repoURL: 'https://github.com/ivofulco/argocd-self-managed.git'
    targetRevision: HEAD
    path: repo-root/addons/external-secret

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secret

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
