replicaCount: 1

image:
  repository: ghcr.io/external-secrets/external-secrets
  tag: "v0.9.19"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

rbac:
  create: true

webhook:
  enabled: true
