apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
data:
  grafana.ini: |
    {{- range $section, $values := .Values.config.grafana_ini }}
    [{{ $section }}]
    {{- range $key, $value := $values }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{ end }}
