apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivofulco/argocd-self-managed  # <- Substitua aqui
    targetRevision: main                                  # ou a branch/tag desejada
    path: gitops/sealed-secrets                                 # pasta onde está o chart                                  # override de valores
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
