apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-cd
- grafana
# - prometheus
#- argo-rollouts
#- keda
#- istio
#- velero
#- popeye
#- kubecost
#- cert-manager
#- lets-encrypt
#- external-secrets
#- graylog
#- kiali
#- kyverno
#- falco