apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  project: somente-leitura
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.0.10
    helm:
      releaseName: 'argocd'
      values: |
        fullnameOverride: 'argocd'
        redis-ha:
          enabled: false
          haproxy:
            resources:
              limits:
                cpu: 1
                memory: 512Mi
        controller:
          replicas: 1
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          service:
            type: LoadBalancer
        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2
        applicationSet:
          replicas: 2
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
