apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.0.0
    helm:
      releaseName: argocd
      values: |
        redis-ha:
          enabled: false

        controller:
          replicas: 1

        server:
          autoscaling:
            enabled: true
            minReplicas: 1

        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 1

        applicationSet:
          replicas: 1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true